const chains = [
    { value: 1, label: "Ethereum Mainnet" },
    { value: 42, label: "Ethereum Testnet Kovan" },
    { value: 137, label: "Matic (Polygon) Mainnet" },
    { value: 80001, label: "Matic (Polygon) Testnet Mumbai" },
    { value: 43114, label: "Avalanche C-Chain Mainnet" },
    { value: 43113, label: "Avalanche Fuji Testnet" },
    { value: 56, label: "Binance Smart Chain" },
    { value: 97, label: "Binance Smart Chain Testnet" },
    { value: 1284, label: "Moonbeam Mainnet" },
    { value: 1287, label: "Moonbeam Moonbase Alpha" },
    { value: 1285, label: "Moonbeam Moonriver" },
    { value: 30, label: "RSK Mainnet" },
    { value: 31, label: "RSK Testnet" },
    { value: 42161, label: "Arbitrum Mainnet" },
    { value: 421611, label: "Arbitrum Testnet" },
    { value: 250, label: "Fantom Opera" },
    { value: 4002, label: "Fantom Testnet" },
    { value: 11297108109, label: "Palm Mainnet" },
    { value: 11297108099, label: "Palm Testnet" },
    { value: 8217, label: "Klaytn Mainnet" },
    { value: 128, label: "HECO Mainnet" },
    { value: 256, label: "HECO Testnet" },
    { value: 71393, label: "Nervos Polyjuice Testnet" },
    { value: 2020, label: "Axie Mainnet" },
    { value: 9001, label: "EVMOS Mainnet" },
    { value: 9000, label: "EVMOS Testnet" },
    { value: 592, label: "Astar Mainnet" },
    { value: 336, label: "Astar Shiden" },
    { value: 4689, label: "IoTeX Mainnet" },
    { value: 4690, label: "IoTeX Testnet" },
    { value: 1666600000, label: "Harmony Mainnet" },
    { value: 1666700000, label: "Harmony Testnet" },
    { value: 1313161554, label: "Aurora Mainnet" },
    { value: 1313161555, label: "Aurora Testnet" },
    { value: 1131378225, label: "Covalent Internal V1" },
]
export default chains
